version: "3"
services:
  python_dev_container:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /project
    volumes:
      - .:/project:cached
      - ${USERPROFILE-~}/.ssh:/home/vscode/.ssh
    image: python_dev_container
    container_name: python_dev_container
    tty: true
    env_file: .env # shellスクリプト内でも環境変数として使用するため
